include: 'https://code.revolt.org/riseup/tcp/containers/glue/raw/no-masters/.gitlab-ci.yml'

# 'build' goes before 'test' because we test the container images
# that we've just built.
stages:
  - build
  - test
  - release

test:
  stage: test
  image: registry.git.autistici.org/ai3/docker/test/python:chromedriver
  services:
    - name: "${IMAGE_TAG}"
      alias: website
  variables:
    APACHE_PORT: 8080
    SITE_URL: "http://website:8080"
    TOX_TESTENV_PASSENV: SITE_URL
  script:
    - cd render-test
    - ulimit -c 0
    - tox --skip-pkg-install
  artifacts:
    when: always
    paths:
      - render-test/screenshots/

